app:
  - title: "palworld-sav-api"
  - description: "Setup to handle http requests for altering the state of the PalWorld game"
  - version: "0.0.1"
  - docs_url: "/docs"
  - root_path: "/"
db:
  - echo_sql: true
log:
  - level: "INFO"
agent:
  - openai_model: "gpt-3.5-turbo-0613"